name: Web API Deploy Pipeline

on:
  push:
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "docker/**"

env:
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: mononoke-book
  ECS_SERVICE: mononoke-2
  ECR_REPOSITORY: portfolio-prod-finish-2
  ECS_TASK_DEFINITION_API: cicd_section/.aws/task-def-api.json

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4


      - name: Set up Docker-Compose
        uses: docker/setup-buildx-action@v2

    # docker-composeのインストール
      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # 使用するPHPのバージョンを指定

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"

      - name: Set up Docker
        run: |
             docker-compose up -d


 # Docker コンテナに入るためのスクリプトを追加
      - name: Enter Docker Container
        run: |
             docker-compose exec -T db mysqladmin --silent --wait=40 -uroot -ppassword ping || exit 1
             docker-compose exec -T test_db mysqladmin --silent --wait=40 -uroot -ppassword ping || exit 1
             docker-compose exec -T app php /var/www/html/src/migration/initialize_all_table.php
             docker-compose exec -T app php /var/www/html/src/migration/tests/initialize_all_table.php
             docker-compose exec -T app composer install
             docker-compose exec -T app npm install
             docker-compose exec -T app composer phpunit

   # Docker コンテナを停止する場合（オプション）


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker images
          docker image tag portfolio-prod-finish-2_app $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          echo $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} > portfolio-image-uri.txt

      - name: Upload the image URI file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: portfolio-image-uri
          path: src/portfolio-image-uri.txt

      - name: Stop Docker Containers
        run: docker-compose down

#Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: [test-and-build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: portfolio-image-uri
          path: artifacts

      - name: Define the image URI
        run: |
          echo "PORTFOLIO_IMAGE_URI=$(cat artifacts/portfolio-image-uri.txt)" >> $GITHUB_ENV

      - name: Fill in the new image URI in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_API }}
          container-name: portfolio
          image: ${{ env.PORTFOLIO_IMAGE_URI }}

      - name: Deploy ECS task
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
